// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNpMGzw5nWd7CbfvuBeoEc05w-0AncUEc',
    appId: '1:85988698552:android:adc5ee233c70098486874d',
    messagingSenderId: '85988698552',
    projectId: 'smartstation-19515',
    storageBucket: 'smartstation-19515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfim-Oba5jJpHJ-eDH-DiylI8I2xn23t8',
    appId: '1:85988698552:ios:267c085a39a7a01186874d',
    messagingSenderId: '85988698552',
    projectId: 'smartstation-19515',
    storageBucket: 'smartstation-19515.appspot.com',
    androidClientId: '85988698552-q3nrqpvg7s5mr52hnfufi0dgl2odqk33.apps.googleusercontent.com',
    iosClientId: '85988698552-2a96d5bj89ps4o5kirk5j2lpvs7jg9e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartStation',
  );
}
